# not to be used in production
version: "3"

services:
    a11y:
        build: .
        ports:
            - 3000:80
        environment: 
            - MONGODB_URI=mongodb://mongo/a11y-req
            - BASICAUTHUSERNAME=admin
            - BASICAUTHPASSWORD=password
            - POPULATE_DB=$${POPULATE_DB}
            - WAITHOSTS=mongo:27017
            - WAITFORMONGO=true
    mongo:
        image: mongo:3.3
        restart: always
    
    mongoexpress:
        image: mongo-express
        restart: always
        ports: 
            - 3005:8081

